### ISSUE TITLE
Loading the file in .SAFE format

### ISSUE THREAD

**Issue by Karlmarx95** [pbrotoisworo/s1-tops-split-analyzer#21]
Dear Pbrotoisworo,

   Thank you for sharing your work on S1-Tops split analyzer (stsa). My question is, whether is it possible to load the image by .SAFE format? because I use code-de virtual machine and get the S1 image only in .SAFE format.  Do you have any idea in it? I also tried to zip my file in the user account of virtual machine but didn't worked.

Thank you.

kind regards,
Karlmarx

**Comment by pbrotoisworo** [comment]
I haven't worked with .SAFE format before but I can try to look into this. Can you show me where to get .SAFE data?

**Comment by Karlmarx95** [comment]
from the code-de virtual machine ([(https://code-de.org/en/)])
